# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ztHYaG3m7WIR0udzXAkxo333xlXTINRO
"""

boys_with_book = 5
boys_n_book = 35
girls_with_book = 20
girls_n_book = 40

p_boys = (boys_with_book+boys_n_book) / 100
p_girls = (girls_with_book+girls_n_book) / 100
p_books = (boys_with_book+girls_with_book) / 100
p_n_books = (boys_n_book+girls_n_book) / 100

p_boy_given_book = boys_with_book/25
p_book_given_boy = (p_boy_given_book*p_books) / p_boys
print(round(p_book_given_boy,2))