# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ztHYaG3m7WIR0udzXAkxo333xlXTINRO
"""

b_have_book = 5
b_n_book = 35
g_have_book = 20
g_n_book = 40

p_b = (b_have_book+b_n_book) / 100
p_g = (g_have_book+g_n_book) / 100
p_books = (b_have_book+g_have_book) / 100
p_n_books = (b_n_book+g_n_book) / 100

p_b_given_book = b_have_book/25
p_book_given_b = (p_b_given_book*p_books) / p_b
print(round(p_book_given_b,2))